cache:
  - key: "$CI_PROJECT_ID"
    untracked: true
    paths:
      - .yarn
  - key: "stage"
    policy: pull-push
    untracked: true


variables:
  DOCKER_DRIVER: overlay2
  REGISTRY_URL: registry.blytd.com
  ANSIBLE_PATH: .playbooks
  STAGE_IMAGE_URL: $CI_REGISTRY/frontend/jobhunt:stage-latest
  PRODUCTION_IMAGE_URL: $CI_REGISTRY/frontend/jobhunt:latest

stages:
  - build
  - stage

build-stage:
  stage: build
  script:
    - docker login -u ci -p $PRIVATE_REGISTRY_PASSWD $REGISTRY_URL
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-args APP_ENV=production-t ${STAGE_IMAGE_URL} .
    - docker push ${STAGE_IMAGE_URL}
  only:
    - develop

deploy-stage:
  image:
    name: williamyeh/ansible:ubuntu18.04
  stage: stage
  script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(cat "$DEVOPS_STAGE_SERVER_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ansible-playbook $ANSIBLE_PATH/playbook.yml --inventory $ANSIBLE_PATH/inventory.yml
  only:
    - develop
