cache:
  - key: "$CI_PROJECT_ID"
    untracked: true
    paths:
      - .yarn
  - key: "stage"
    policy: pull-push
    untracked: true


variables:
  DOCKER_DRIVER: overlay2
  REGISTRY_URL: registry.blytd.com
  ANSIBLE_PATH: .playbooks
  ANSIBLE_PRODUCTION_PATH: .ansible
  STAGE_IMAGE_URL: $CI_REGISTRY/frontend/jobhunt:stage-latest
  PRODUCTION_IMAGE_URL: $CI_REGISTRY/frontend/jobhunt:latest

stages:
  - build
  - stage

build-stage:
  stage: build
  script:
    - docker login -u ci -p $PRIVATE_REGISTRY_PASSWD $REGISTRY_URL
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg APP_ENV=stage -t ${STAGE_IMAGE_URL} .
    - docker push ${STAGE_IMAGE_URL}
  only:
    - develop

deploy-stage:
  image:
    name: williamyeh/ansible:ubuntu18.04
  stage: stage
  script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(cat "$DEVOPS_STAGE_SERVER_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ansible-playbook $ANSIBLE_PATH/playbook.yml --inventory $ANSIBLE_PATH/inventory.yml
  only:
    - develop


build-production:
  stage: build
  script:
    - docker login -u ci -p $PRIVATE_REGISTRY_PASSWD registry.blytd.com
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${PRODUCTION_IMAGE_URL} .
    - docker push ${PRODUCTION_IMAGE_URL}
  only:
    - /^v\d+\.\d+\.\d+$/ 


deploy-production:
  image: gableroux/ansible:4.5.0
  stage: stage
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$DEVOPS_PRODUCTION_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ansible-galaxy install -r $ANSIBLE_PRODUCTION_PATH/requirements.yml
    - ansible-playbook $ANSIBLE_PRODUCTION_PATH/main.yml --inventory $ANSIBLE_PRODUCTION_PATH/production
  only:
    - /^v\d+\.\d+\.\d+$/
  when: manual

