---
- name: continues delivery
  hosts: stage
  user: devops

  vars:
    ansible_python_interpreter: /usr/bin/python3
    dest_path: /srv/stage/jobhunt.front.stg.blytd.com

  tasks:
    - name: create necessary directories
      file:
        path: "{{ dest_path }}"
        state: directory
        owner: devops
        group: devops

    - name: copy compose file
      template:
        src: docker-compose.yml
        dest: "{{ dest_path }}/docker-compose.yml"

    - name: Get the latest build
      shell: docker-compose pull
      args:
        chdir: "{{ dest_path }}"

    - name: bring up the containers
      shell: docker-compose up -d
      args:
        chdir: "{{ dest_path }}"

